### ISSUE TITLE
Fn dependency 

### ISSUE THREAD

**Issue by wannaknowmo** [getlazy/faas-pipeline#1]
Hi 
Is it possible to start another fn after fn1 executed successfully (fn4) while fn2 & fn2 are still running?

**Comment by ierceg** [comment]
If I understand you correctly that would be something like this:

```
pipeline:
	~pipe:
		- ~split:
			~pipe:
				fn1:
				fn4:
			fn2:
			fn3:
```

**Comment by wannaknowmo** [comment]
Fn1 2 3 start at the same time while fn4 will only start if fn1 was successful.

Thanks for the quick reply

**Comment by alexellis** [comment]
Hey guys super interesting project.. are you still working on it?

I've added it to the OpenFaaS community page :-) https://github.com/openfaas/faas/blob/master/community.md#repos---projects--samples--use-cases
